cache_run_c_code = 'Test does not build: Traceback (most recent call last):\n  File "/Users/uceeoas/Codes/temp/ns-3-inrpp/.waf-1.7.16-9ca17eb492c97b689870b4ff9db75880/waflib/Tools/c_config.py", line 460, in run_c_code\n    bld.compile()\n  File "/Users/uceeoas/Codes/temp/ns-3-inrpp/.waf-1.7.16-9ca17eb492c97b689870b4ff9db75880/waflib/Build.py", line 188, in compile\n    raise Errors.BuildError(self.producer.error)\nBuildError: Build failed\n -> task in \'testprog\' failed (exit status 1): \n\t{task 4508370832: cxxprogram test.cpp.1.o -> testprog}\n[\'/opt/local/bin/g++\', \'-L/opt/local/lib\', \'-L/opt/local/lib\', \'-arch\', \'x86_64\', \'-arch\', \'i386\', \'-Wl,-F.\', \'-arch\', \'x86_64\', \'-arch\', \'i386\', \'test.cpp.1.o\', \'-o\', \'/Users/uceeoas/Codes/temp/ns-3-inrpp/build/.conf_check_1f933b02106127ce3a9f4633a0e368e7/testbuild/testprog\', \'-L/System/Library/Frameworks/Python.framework/Versions/2.7/lib\', \'-lpython2.7\']\n'
